title: Chloe's Content Collection

author:
  name: William Cougan
  email: william.cougan@gmail.com
  
description: >
  Stories, lullabies, and content written just for little Chloe.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
